name: dart_codes_najot_talim
description: Code snippets written in Dart at "Najot Ta'lim" Bootcamp course
version: 1.0.0

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  http: ^1.2.1


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
